@URL=http://localhost/backend


### Criar um usuário
POST {{URL}}/user/create.php
Content-Type: application/json

{
    "nome": "Juca da Silva",
    "email": "juca4@gmail.com",
    "senha": "1234",
    "perfil": "user"
}


### Atualizar um usuário
POST {{URL}}/user/update.php?email=juca2@gmail.com
Content-Type: application/json

{
    "nome": "Juca da Silva",
    "email": "juca2@gmail.com",
    "senha": "juquinha2",
    "perfil": "user"
}


### Obter todos os usuários
POST {{URL}}/user/list.php
Content-Type: application/json

{
    "email": ""
}


### Obter um usuário pelo EMAIL
POST {{URL}}/user/list.php
Content-Type: application/json

{
    "email": "juca2@gmail.com"
}

### Deletar um usuário
POST {{URL}}/user/delete.php
Content-Type: application/json

{
    "email": "juca4@gmail.com"
}